---
version: '2'
services:
  web:
    image: nginx
    volumes:
      - ./nginx-config:/etc/nginx/templates
      - ./htdocs:/data/htdocs
    ports:
      - 127.0.0.1:8080:80

  redis:
    image: redis:latest
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis-data:/data

  timescale:
    image: timescale/timescaledb:latest-pg11
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - timescale-data:/var/lib/postgresql/data

  ttn-redis-producer:
    build: ttn-redis-producer
    restart: always
    links:
      - redis:redis
    environment:
      REDIS_URL: redis://redis:6379/0
    env_file:
     - secrets.env
     - ttn-redis-producer/config.env

  ttn-redis-decoder:
    build: ttn-redis-decoder
    restart: always
    links:
      - redis:redis
      - timescale:timescale
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:password@timescale:5432/postgres
    env_file:
     - ttn-redis-decoder/config.env

  ttn-redis-converter:
    build: ttn-redis-converter
    restart: always
    links:
      - redis:redis
    environment:
      REDIS_URL: redis://redis:6379/0
    env_file:
     - secrets.env
     - ttn-redis-converter/config.env

volumes:
  redis-data:
  timescale-data:
