---
version: '2'
services:
  web:
    image: nginx
    volumes:
      - ./nginx-config:/etc/nginx/templates
      - ./htdocs:/data/htdocs
    ports:
      - 127.0.0.1:8080:80
    environment:
      - SENSORHUB_URL=https://osh:443/
    links:
      - osh:osh

  redis:
    image: redis:latest
    restart: always
    ports:
      # For testing scripts outside docker
      - 127.0.0.1:63790:6379
    volumes:
      - redis-data:/data

  timescale:
    image: timescale/timescaledb:latest-pg11
    restart: always
    ports:
      # For testing scripts outside docker
      - 127.0.0.1:54320:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - timescale-data:/var/lib/postgresql/data

  ttn-redis-producer:
    build: ttn-redis-producer
    restart: always
    links:
      - redis:redis
    environment:
      REDIS_URL: redis://redis:6379/0
    env_file:
     - secrets.env
     - ttn-redis-producer/config.env

  ttn-redis-decoder:
    build: ttn-redis-decoder
    restart: always
    links:
      - redis:redis
      - timescale:timescale
      - web:web
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:password@timescale:5432/postgres
      # TODO: Use external DNS name if we have it later?
      CONSYS_URL: http://web/sensorhub/consys
    env_file:
     - ttn-redis-decoder/config.env

  ttn-redis-converter:
    build: ttn-redis-converter
    restart: always
    links:
      - redis:redis
    environment:
      REDIS_URL: redis://redis:6379/0
    env_file:
     - secrets.env
     - ttn-redis-converter/config.env
    # Temporarily prevent this from running
    restart: 'no'
    command: /bin/true

  osh:
    # This refers to a locally built image
    image: osh-node-dev-template_osh:latest
    volumes:
      - osh-data:/opt/opensensorhub/data
      - ./osh-log:/opt/opensensorhub/data/log

  # Additional setup:
  # http://localhost:8080/sensorhub/admin
  #  - Move Sensorweb service to /sensorweb
  #  - Create Consys service on /consys, select existing database,
  #    disable authentication
  #  - Update Network -> HTTP Server -> Proxy Base URL to
  #    http://localhost:8080/
  #  - docker-compose exec osh chown osh: /opt/opensensorhub/data/log

volumes:
  redis-data:
  timescale-data:
  osh-data:
