#!/bin/sh -e

# Small scripts to set random frost user passwords


# Ensure frost is running
docker compose up -d frost-db frost-web

# Authenticate so frost creates user tables
docker compose exec frost-web curl --retry 10 --retry-connrefused -u read:read "http://localhost:8080/FROST-Server/v1.1/Things"

for USER in read write admin; do
    PW=$(openssl rand -hex 16)
    docker compose exec frost-db psql -U frost frost -c "UPDATE \"USERS\" SET \"USER_PASS\"='$PW' WHERE \"USER_NAME\"='$USER';"

    if [ "$USER" = "write" ]; then
        echo "SENSORTHINGS_PASSWORD=$PW" >> secrets.env
    fi
done

echo "Modified all user passwords, stored write password in secrets.env"
