[tool.poetry]
name = "legacy-convert"
version = "0.1.0"
description = ""
authors = ["Matthijs Kooijman <matthijs@stdin.nl>"]
license = "CC0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
redis = "^5.3.1"
pony = "^0.7.19"
psycopg2-binary = "^2.9.11"
iso8601 = "^2.1.0"
requests = "^2.32.5"
bitstring = "^4.3.1"
deepdiff = "^8.6.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
