#!/bin/sh

. ./config.env
. ../secrets.env

export REDIS_URL="redis://mjs-backend-design-redis-1:6379/0"
export REDIS_STREAM
export DATABASE_URL="postgres://postgres:password@mjs-backend-design-timescale-1:5432/postgres"
export SENSORTHINGS_URL="http://mjs-backend-design-frost-web-1:8080/FROST-Server/v1.1"

poetry run python app.py "$@"
