[tool.poetry]
name = "ttn-save-msg"
version = "0.1.0"
description = ""
authors = ["Matthijs Kooijman <matthijs@stdin.nl>"]
license = "CC0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
redis = "^7.0.1"
iso8601 = "^2.1.0"
psycopg2-binary = "^2.9.11"
duckdb = "^1.5.0"
pytz = "^2026.1.post1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
